# Generated by Django 6.0.3 on 2026-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_code', models.CharField(max_length=50, unique=True, verbose_name='规格编码')),
                ('spec_name', models.CharField(max_length=100, verbose_name='规格名称')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('is_delete', models.IntegerField(default=0, verbose_name='删除标志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
