# Generated by Django 6.0.3 on 2026-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='machine_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='售货机ID'),
        ),
    ]
