# Generated by Django 6.0.3 on 2026-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('machine_id', models.IntegerField(verbose_name='售货机ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID（可为空表示匿名购买）')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实付金额')),
                ('order_type', models.IntegerField(default=1, verbose_name='订单类型')),
                ('pay_type', models.IntegerField(default=1, verbose_name='支付方式')),
                ('pay_status', models.IntegerField(default=0, verbose_name='支付状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('order_status', models.IntegerField(default=0, verbose_name='订单状态')),
                ('device_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备编号')),
                ('cabinet_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='取餐柜编号')),
                ('pickup_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='取餐码')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(verbose_name='订单ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('aisle_id', models.IntegerField(verbose_name='货道ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称（冗余字段）')),
                ('product_image', models.CharField(max_length=200, verbose_name='商品图片（冗余字段）')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计金额')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本单价（冗余字段）')),
                ('remark', models.TextField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 't_order_detail',
            },
        ),
    ]
